name: "Macos"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - run: nix build
      - run: nix flake check
      - run: npm install
      - run: npm run test
